### ISSUE TITLE
Identify reverse dependencies of request & alert package authors to upcoming changes

### ISSUE THREAD

**Issue by titaniumbones** [tkf/emacs-request#101]
I'm not sure if there's an easy way to get a list of all reverse dependencies of a package in MELPA, but if one could, it would be polite to let authors know that files will now be encoded to utf-8 by default.  I have seen at least one workaaroud that involves pre-encoding text to binary before saving, and I expet that will break now.

**Comment by titaniumbones** [comment]
visible in melpa so should be easy to do this; see [page for request](https://melpa.org/#/request) and for [request-deferred](https://melpa.org/#/request-deferred).

**Comment by dickmao** [comment]
Unfortunately, some breakage is expected
millejoh/emacs-ipython-notebook#567
louietan/anki-editor#51

#128 attempts to mitigate some of the fallout.
