### ISSUE TITLE
ensure Makefile uses system emacs rather than aliased emacsclient

### ISSUE THREAD

**Issue by titaniumbones** [tkf/emacs-request#107]
Some users of oh-my-zsh (including @titaniumbones)  alias `emacs` to a shell script that calls emacsclient. It would be ocnvenient if the Makefile distinguished between the executable emacs and the alias, i na shell-neutral way.

- [ ] learn how makefiles access shell info
- [ ] implement :-)

**Comment by dickmao** [comment]
The standard way of specifying an alternative emacs binary in `make` is:
```
EMACS=my-emacs-snapshot make
```
