### ISSUE TITLE
Using `curl` on Windows: `"exited abnormally with code 2"` error

### ISSUE THREAD

**Issue by nikclayton** [tkf/emacs-request#111]
`request.el` defaults to using Curl if it's available.

Windows (at least v10) currently ships an old version:

```
% where curl
C:\Windows\System32\curl.exe
% curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

I haven't dug in to why, but `request.el` can't use this version. You get `"exited abnormally with code 2"` errors.

The solution was to change `request-backend` to use `url-retrieve`. You might want to either (a) make this the default on Windows, or, at least, if the curl executable is in the C:\Windows\System32, log a prominent message somewhere that its use is problematic.

See this related issue in `org-gcal`: https://github.com/myuhe/org-gcal.el/issues/46#issuecomment-390106057

**Comment by titaniumbones** [comment]
Thanks @nikclayton . if you are at all able to make a PR against the [development branch](https://github.com/tkf/emacs-request/tree/development) please do so. This package is mostly orphaned and the rest of us are just filling in here where we can.   I don't have access to Windows so I can't do any testing myself, and in any case I personally won't be able to turn to this for a couple of weeks at the least.

Thank you!

**Comment by dickmao** [comment]
A field observation: most out-of-the-box Windows versions of curl do not support `request.el`'s insistence on the `--compressed` switch.  Windows users are mostly on their own as we do not test on that platform.  As always, we rely on users so fed up with the brokenness of the status quo to do something about it (*groan*).  Sorry.
