### ISSUE TITLE
Add to GNU ELPA so that other ELPA packages can use it as a dependency?

### ISSUE THREAD

**Issue by phil-s** [tkf/emacs-request#112]
Looking at:
https://www.reddit.com/r/emacs/comments/avfm9x/asynchronous_operation_not_really_asynchronous/

It seems that request.el addresses a genuine problem with the core functionality for handling URLs.  The request.el file suggests that it may already have FSF copyright assignment (?).  Could the package be added to GNU ELPA so that other GNU ELPA packages can specify it as a dependency?  (And so that it might also feasibly be added to Emacs at some point.)

**Comment by dickmao** [comment]
The path to ELPA can be onerous indeed.  Alas, we rely on users with enough interest in this endeavor to do something about it.  Sorry.
