### ISSUE TITLE
Guaranteed completion after timeout

### ISSUE THREAD

**Issue by matthew-piziak** [tkf/emacs-request#114]
Is it true that if `:timeout` is `2`, then after two seconds `:complete` should run?

**Comment by matthew-piziak** [comment]
As far as I can tell it is _not_. This is causing me trouble, since I want to be able to give up within a bounded amount of time and guarantee that some cleanup code runs.

**Comment by matthew-piziak** [comment]
Basically I want to have a bit of code run after timeout and I can't find anything in the documentation that lets me do this.

**Comment by dickmao** [comment]
Can you close this if #113 resolves the matter?

**Comment by matthew-piziak** [comment]
Ah yes, thank you.
