### ISSUE TITLE
request-deferred.el depends on old request.el version 

### ISSUE THREAD

**Issue by kaiwk** [tkf/emacs-request#117]
It seems latest version of request.el is 0.3.0.

https://github.com/tkf/emacs-request/blob/db88fd21d25399ff9940c208173665b12493992b/request.el#L10

But now request-deferred.el depend on request.el 0.2.0.

https://github.com/tkf/emacs-request/blob/db88fd21d25399ff9940c208173665b12493992b/request-deferred.el#L7

Is this a negligence?

**Comment by dickmao** [comment]
> Is this a negligence?

No?  `Package-Requires` specifies at least a version of 0.2.0, and we assume later will work too.

If I make a 0.4.0, it would be onerous indeed if I had to re-specify for everyone who depended on me.

**Comment by kaiwk** [comment]
> Package-Requires specifies at least a version of 0.2.0

Thanks, that makes sense to me.
