### ISSUE TITLE
Report auto-revert/inotify issue upstream

### ISSUE THREAD

**Issue by titaniumbones** [tkf/emacs-request#153]
When upstream bug has been reported, link here, preferably in title.  Keep open as tracker until upstream is fixed and fix is released, at which point internal cleanup can be undertaken. 

cf [discussion here](https://github.com/tkf/emacs-request/pull/152#issuecomment-544905721) and other links in that discussion. 

Tagging @alphapapa as I expect my initial bug report will be somewhat technically deficient, when I get around to it (hopefully 1-2 days)

**Comment by dickmao** [comment]
The emacs maintainer [appears to be familiar]( https://www.reddit.com/r/emacs/comments/eewwyh/officially_introducing_memacs/fbzr8ms?utm_source=share&utm_medium=web2x) with this issue.

>  `(global-auto-revert-mode t)`
> Not a good idea ... the above brings Emacs to its knees and it becomes extremely unresponsive,
> for as long as that I/O-extensive job runs. At the very least, turn off auto-revert-use-notify or 
> customize auto-revert-notify-exclude-dir-regexp to exclude I/O intensive directories from auto-reverting.

**Comment by alphapapa** [comment]
@dickmao If I understand correctly, you're agreeing that, in general, Emacs users should not be enabling `global-auto-revert-mode`, and therefore that `request` should not be doing anything with it.

However, `request-testing.el` is still enabling the mode: https://github.com/tkf/emacs-request/blob/d2957086f5012e8a5dd5cfaedf8fec778f69e6e2/tests/request-testing.el#L44  That means that whenever a user loads `request-testing.el` (e.g. to run some `request` tests in a running Emacs instance), `global-auto-revert-mode` will be enabled in the user's Emacs session.  Probably, it will not even be noticed by the user, but the negative side effects may be noticed (likely confusing the user as to why they are happening).

So are you going to remove that code from the test file?

**Comment by dickmao** [comment]
Okay, thanks.
