### ISSUE TITLE
document use of `development` branch

### ISSUE THREAD

**Issue by titaniumbones** [tkf/emacs-request#154]
We created a `development` branch in late 2018 to enable centralized dev work outside of master. This should be documented in README & probably `development` should be set as default PR target.  Tagging @dickmao to make sure you're cool with this idea, after which I can implement.

**Comment by dickmao** [comment]
A "uat" or development branch is useful when a significant number of users actually beat on it for their day-to-day.  That isn't the case for this little repo.

The merge in June of `development` contained two significant bugs, 1. the `:sync t` deadlocks, and 2. failures resulting from `utf-8` reformatting, neither of which could have been caught by slow marination in `development`.

If you insist on making `development` a thing, well, I suppose that's harmless and I don't think anyone particularly cares.  Note `melpa-stable` does exist for the easily ruffled, but that route is its own can of worms.
