### ISSUE TITLE
`request--file-url' broken

### ISSUE THREAD

**Issue by jktomer** [tkf/emacs-request#164]
The `request--file-url` test fails at head for me:

```
Test request--file-url condition:

    (ert-test-failed
     ((should
       (string= body
		(request-response-data got)))
      :form
      (string= "hello, world
" "Content-Length: 14
Accept-ranges: bytes
Last-Modified: Tue, 26 Nov 2019 21:52:27 GMT

hello, world
")
      :value nil))

   FAILED  10/46  ( 0.09s)  request--file-url
```

As far as I can tell, this is expected:
```shell
$ curl --silent --include --location file:///tmp/emacs-request4vqkgz
Content-Length: 14
Accept-ranges: bytes
Last-Modified: Mon, 25 Nov 2019 18:17:44 GMT

hello, world
```

Curl seems to fabricate HTTP response headers for file URLs. If we don't want it to do that, we should not pass `--include` for `file://` URLs. If we do, we shouldn't assert that they are absent in this test.

**Comment by dickmao** [comment]
Indeed, the effort to accommodate `file://` URLs was [relatively recent](https://github.com/tkf/emacs-request/pull/127#issuecomment-513006686), and made the code a [tad messier](https://github.com/tkf/emacs-request/blob/0733373886f37bab047c5998bf4de665985d23ab/request.el#L657-L660).

Our experience has been that curl does not include the header for `file://` URLs even with `--include`.  What version of curl and what OS are you using?  I suspect I will have to stop depending on this particular assumption about curl's output or perhaps even remove support for `file://` URLs.

**Comment by jktomer** [comment]
```
:( 15:22 crab:jktomer[9901]~% echo hello > /tmp/foo.txt
:) 10:26 crab:jktomer[9902]~% curl -i file:///tmp/foo.txt
Content-Length: 6
Accept-ranges: bytes
Last-Modified: Wed, 11 Dec 2019 18:26:55 GMT

hello
:) 10:26 crab:jktomer[9903]~% curl --version
curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.39.2 librtmp/2.3
Release-Date: 2019-09-11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
:) 10:27 crab:jktomer[9904]~% 
```

**Comment by dickmao** [comment]
Thanks.
