### ISSUE TITLE
How do I make a GET request and parse the json output into a elisp structure?

### ISSUE THREAD

**Issue by olav35** [tkf/emacs-request#183]
Hello

This library looks like what I need for a project.

I just learnt elisp today and I couldn't understand the code examples. I want to make a GET request and parse the json output I get into a elisp data structure. Like a dictionary/hash table/associative array.

How could I do this?

I'm sorry if this is a stupid question. I just started learning elisp today.

**Comment by dickmao** [comment]
The README example already parses the json response into an elisp "associated list."

I would spend at least a few hours playing with the builtin [lisp interaction mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Lisp-Interaction.html#Lisp-Interaction).  There is unfortunately a lot to know.

The prevailing venues for asking elisp questions would seem emacs.stackexchange.com or reddit, but not here.  Thanks for your interest.
