### ISSUE TITLE
url-retrieve POST data encoding

### ISSUE THREAD

**Issue by nivekuil** [tkf/emacs-request#185]
url-retrieve seems to expect its POST data (and likely other fields) to be properly encoded beforehand.  Otherwise, it throws a `Multibyte text in HTTP request` error.

So in order to handle sending utf-8 data like “fancy quotes”, I have to pass `:data` like so:
```
(request "http://localhost:8080/query"
      :type "POST"
      :data (if (multibyte-string-p query) (encode-coding-string query 'utf-8) query)
...
```
Likewise to get the data of the response in the success callback, I have to do: 
```
(decode-coding-string (request-response-data response) 'utf-8))
```
or else that fancy quote just looks like `\342\200\234`.

I think this should be handled in request.el, or at least documented as a gotcha.

**Comment by dickmao** [comment]
I see what you mean.

If the four-year-old discussion surrounding [Bug#23750](https://github.com/emacs-mirror/emacs/blob/master/lisp/url/url-http.el#L416) wasn't going to make a judgment call about multibyte handling (and just begs off with an error) then I'd rather the humble abstraction of request.el remain similarly noncommital.
