### ISSUE TITLE
Incorrect flags passed to curl with :auth

### ISSUE THREAD

**Issue by DavidTruby** [tkf/emacs-request#187]
When I try use the :auth option, the code following it gets passed to curl verbatim so the curl call fails.
For example:

```elisp
(request
   "https://example.com"
   :type "POST"
   :data `(("data" . "some_data"))
   :auth '(:user "truby"))
```

passes the flag `--(:user "truby")` to curl, which it doesn't understand.

**Comment by dickmao** [comment]
`:auth` needs to be one of `basic`, `digest`, `anyauth`, i.e., one of the various curl authentication flags.

I've only ever tested `digest` so it's not clear how well some of the other methods work.

**Comment by DavidTruby** [comment]
Oh ok! It wasn't clear to me from reading the PR that introduced it that that was the case (I was following the example given in the PR). Some documentation of how this flag works would be great, and maybe a warning if the flag is wrong?
I can look at doing that if it's a PR you'd be interested in :)

**Comment by dickmao** [comment]
You got it.  d02d134
