### ISSUE TITLE
get/post to sites in https using certificates

### ISSUE THREAD

**Issue by matteoredaelli** [tkf/emacs-request#194]
I can do get/post requests to website in https using certificates. I'd like to d the same with this package.

is it possibile?

Regards
M

**Comment by dickmao** [comment]
Maybe something like:
```
(let ((request-curl-options (split-string "--key ./admin-key.pem --cert ./admin.pem"))
      (request-backend 'curl))
  (request "https://example.com"))
```
You'll have to play around with `request-curl-options`.
