### ISSUE TITLE
Hope request.el included in GNU ELPA

### ISSUE THREAD

**Issue by stardiviner** [tkf/emacs-request#195]
The request.el is really a wide used url.el wrapper library between Emacs Lisp developers.
So I suggest @tkf you can consider put requets.el on GNU ELPA. What do you think?
(I have emailed you some days ago, but have not got any response, so I try to contact you on this GitHub, hope you don't mind. If it distrubutes you, I'm sorry in advance)

**Comment by alphapapa** [comment]
https://github.com/tkf/emacs-request/issues/112

**Comment by stardiviner** [comment]
I see. I will close this issue. @alphapapa thanks for helping. 😄
