### ISSUE TITLE
Adding to NonGNU ELPA

### ISSUE THREAD

**Issue by monnier** [tkf/emacs-request#196]
I just added `request` to the new NonGNU ELPA archive at https://elpa.nongnu.org/nongnu/

New releases will be made whenever the `Version:` header changes and an announcement will be Cc'd to the author/maintainer, which will fail here since the `Author:` doesn't contain a valid email address.
It would be good to fix it (similarly, I wish the `git log` would show more informative info than "dickmao <none>").

I decided to keep `doc`, `tests` and `COPYING` out of the tarball.  That was fairly arbitrary.  I recommend you make this decision on your side instead, which you can do by adding a `.elpaignore` file in which you list the elements that shouldn't be included in the tarballs.

**Comment by dickmao** [comment]
Noted.
