### ISSUE TITLE
Safer alternative to passing curl options on the command line (e.g. to not reveal secrets to other users on the system)

### ISSUE THREAD

**Issue by alphapapa** [tkf/emacs-request#202]
Hi @dickmao,

For a few years, I've been somewhat uncomfortable with using curl for HTTP in Emacs, because some sensitive data, like access tokens in HTTP headers, are passed to curl on the command line, which is usually visible to other users on the system.  Despite that, I've used it in some of my projects, like [Ement.el](https://github.com/alphapapa/ement.el), but I've always wanted to solve this issue somehow.

In the past I had seen curl's `--config` option, but the man page didn't describe using it when also passing request bodies via STDIN, so I guessed that it wasn't possible.  I also found a very old post on the curl mailing list (I've since lost that URL, but it's there somewhere) asking for more ways to pass data to curl without revealing it on the command like, but the request and proposed solution were rejected.

However, today I did some experimenting, and I found a way to make it work, even though the man page doesn't describe the details.  It's simple enough, and it allows passing, e.g. `--header` options via STDIN, followed by any request data, either text or binary.  This would seem to make using curl in Emacs much more secure, generally.  I'm certainly more comfortable using it for, e.g. Matrix, in which every request passes auth tokens in HTTP headers.

So, having discovered this (not that I'm the first to, but anyway), I wanted to share it with you so that maybe `request.el` can also benefit from it, since many Emacs packages rely on it.  Here's the commit I just made to `plz.el`, my little Emacs curl library, that shows how it works: https://github.com/alphapapa/plz.el/commit/f2176dc56c379b5d4676f5cd7c3511bd1399e53a

Thanks for your work maintaining `request`.

**Comment by dickmao** [comment]
Great, thanks.
