### ISSUE TITLE
Pass user agent to curl

### ISSUE THREAD

**Issue by thanhvg** [tkf/emacs-request#204]
Before the recent change I was able to pass user agent like this:
``` elisp
(setq my-user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36")
(let ((request-curl-options `(,(format "-A %s" my-user-agent))))
    (request "blah blah"))
```

Now I am no longer able to do so, it seems that the user string is split by space and only the first word is taken and so the actual user agent emacs-request sends is `Mozilla/5.0`.

Bellow is a snippet to reproduce my problem:
``` elisp
(setq my-user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36")

(let ((request-curl-options `(,(format "-A %s" my-user-agent))))
  (request "http://httpbin.org/get"
    :params '(("key" . "value") ("key2" . "value2"))
    :parser 'json-read
    :success (cl-function
              (lambda (&key data &allow-other-keys)
                (message "Header sent: %S" (assoc-default 'User-Agent (assoc-default 'headers data)))))))

```

Can you suggest a way to make it work again? 

Thanks.

**Comment by dickmao** [comment]
Enclosing the user-agent in double quotes seems like an inoffensive way to get
around this problem, e.g., `(format "-A \"%s\"" my-user-agent)`.
