### ISSUE TITLE
Docs url is wrong

### ISSUE THREAD

**Issue by togakangaroo** [tkf/emacs-request#205]
It is not `https://tkf.github.com/emacs-request/` it is `https://tkf.github.io/emacs-request/`

Also the internal links within the documentation seem to make the same error

**Comment by dickmao** [comment]
Okay, brah.

**Comment by Croissong** [comment]
It's still wrong in the repo description :sweat_smile:

**Comment by dickmao** [comment]
That cannot be helped.  Only the repo owner can change that.
