### ISSUE TITLE
PATCH request method

### ISSUE THREAD

**Issue by sienic** [tkf/emacs-request#209]
Would it be possible to add support to `PATCH` requests?

If so, happy to help, but would appreciate some hint on where to make changes.
Thanks.

**Comment by dickmao** [comment]
There's no mention of `PUT` in `request.el` so I assume setting `:type PATCH` will just work.

So the question really becomes whether you want to update `testserver.py` to accommodate `PATCH` and test it, which I doubt you do.

**Comment by sienic** [comment]
You are right, I was using the library incorrectly.
So by using `json-encode` and setting the correct header, I could make a `PATCH` request.
Thanks.
