### ISSUE TITLE
Debugger entered--Lisp error: (void-function request)

### ISSUE THREAD

**Issue by soilc** [tkf/emacs-request#216]
Debugger entered--Lisp error: (void-function request)
  (request "http://httpbin.org/get" :params '(("key" . "value") ("key2" . "value2")) :parser 'json-read :success #'(lambda (&rest --cl-rest--) "\n\n(fn &key DATA &allow-other-keys)" (let* ((data (car (cdr ...)))) (message "I sent: %S" (assoc-default 'args data)))))
  (progn (request "http://httpbin.org/get" :params '(("key" . "value") ("key2" . "value2")) :parser 'json-read :success #'(lambda (&rest --cl-rest--) "\n\n(fn &key DATA &allow-other-keys)" (let* ((data (car ...))) (message "I sent: %S" (assoc-default 'args data))))))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)

**Comment by dickmao** [comment]
This command-line invocation of emacs is a bit above your pay grade, but it demonstrably proves the basic case:

```
git clone https://github.com/tkf/emacs-request.git my-request.el
cd ~/emacs-request
emacs -Q --batch -L . -l request --eval \
"(request \"http://httpbin.org/get\" \
  :params (quote ((\"key\" . \"value\") (\"key2\" . \"value2\"))) \
  :parser (quote json-read) \
  :sync t \
  :success (cl-function \
            (lambda (&key data &allow-other-keys) \
              (message \"I sent: %S\" (assoc-default (quote args) data)))))"
```
*Output*:
```
I sent: ((key . "value") (key2 . "value2"))
```
There's a lot to know about emacs, the first being how to install a package, and then require'ing it.

**Comment by soilc** [comment]
I thought that smart people like you should understand that the package is already installed according to the instructions given: 
M-x package-refresh-contents RET
M-x package-install RET request RET

So, you can see it:
Package request is installed.

     Status: Installed in ‘request-0.3.3/’. Delete
    Version: 0.3.3
    Summary: Compatible layer for URL request in Emacs
   Requires: emacs-24.4
    Website: https://github.com/tkf/emacs-request
 Maintainer: Takafumi Arakaki <aka.tkf at gmail.com>
     Author: Takafumi Arakaki <aka.tkf at gmail.com>
Other versions: 0.3.3 (nongnu), 20221022.1122 (melpa).

**Comment by dickmao** [comment]
> I thought that smart people like you

Sorry, you must be mistaking me for someone else.

**Comment by soilc** [comment]
Why did you close the question?

**Comment by soilc** [comment]
> This command-line invocation
Yes, it works. But I see that 'request.el' from 'my-request.el' is different from the 'request.el' file that was installed via 'M-x install-package request'. Isn't this a problem?

**Comment by soilc** [comment]
I see that you are a writer, not a reader. Therefore, I will repeat.
The problem is in your poor instruction (https://github.com/tkf/emacs-request). And the correct answer to my question is a lack of the '(require 'request)' in my  'init.el'. That's all you need for the right answer.

**Comment by dickmao** [comment]
> I see that you are a writer, not a reader.

Odd that you mention it.  I just finished all 1300 pages of *Les Miserables* by Hugo.  The musical was better.
