### ISSUE TITLE
MELPA?

### ISSUE THREAD

**Issue by Silex** [tkf/emacs-request#22]
Hello,

How about adding this to MELPA so other developers can use it? :)

If you don't have time for it I can take care of it myself (it's as simple as creating a PR, but it's nice to get the author green light before doing so).

**Comment by ardumont** [comment]
It's already on it.
http://melpa.org/#/request

For melpa stable, it's still missing the git tag 0.2.0 though #18

**Comment by ardumont** [comment]
It's also on marmalade https://marmalade-repo.org/packages/request

**Comment by ardumont** [comment]
And on el-get https://github.com/dimitri/el-get/blob/411feeb4b584c451bf2b88f49d2f6f835283c441/recipes/request.rcp

**Comment by ardumont** [comment]
This can be close.
Also, note that #18 has been closed because now melpa-stable has kept up with 0.2.0 version thanks to @abingham.

Cheers,

**Comment by Silex** [comment]
Heh, for some reasons I missed all your comments :cry: 

Perfect, thanks!
