### ISSUE TITLE
what happens when success callback called multiple times concurrently

### ISSUE THREAD

**Issue by mooseyboots** [tkf/emacs-request#224]
in my call to request, the success callback function pushes an id number received in a response to a list stored in a variable.

if the call is made multiple times, a second one starting before the first completes, only the id of the second request is pushed, the first one is lost.

this had me wondering if the value of the variable containing the list is determined not when the success callback is called, but when request is called itself, as at the time of request being called a second time, the first id has not yet been pushed to it.

it could be another issue, but i thought to check if anyone can confirm how such callbacks should work.

as it stands, i don't know how to or if success callbacks can be debugged in order to check.

**Comment by dickmao** [comment]
```
(require 'request)
(let* ((lst nil)
       (callback (lambda (id* &rest _args) (push id* lst)))
       (times 12))
  (dotimes (i times)
    (request "https://example.com" :complete (apply-partially callback i)))
  (while (not (= (length lst) times))
    (accept-process-output nil 0.1))
  lst)
```
Nothing gets lost.
