### ISSUE TITLE
how to use json-encode dynamicly

### ISSUE THREAD

**Issue by spiderbit** [tkf/emacs-request#24]
I know its not a bug in requests but the emacs json package has no real website so I try it here.

(let((url 123))
(json-encode '(("item" . url))))

in this example encode threads url like a string it does not use the value of the symbol url but its name.

Is this just a huge bug and do I really have to write the hole encoded strings manually as only workaround?

**Comment by kosh04** [comment]
Try using ` (blockquote) and , (comma) lists.

http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html

```emacs-lisp
(let((url 123))
  (json-encode `(("item" . ,url))))
;=> "{\"item\":123}"
```

**Comment by syohex** [comment]
Thanks @kosh04.

**Comment by spiderbit** [comment]
somehow did not see this answer, or did not notice it.

I think I worked around it in my code:
  (setq json (json-encode '(("id" . 1)("jsonrpc" . "2.0")("method" . "Playlist.Add")("params" . (("playlistid" . 1)("item" .  (("file" . "url"))))))))
  (setq json-with-url (replace-regexp-in-string "url" url json))

in kode-remote.el

when I have time I rewrite and test it again, so thx from me, too.
