### ISSUE TITLE
`HEAD` doesn't work with curl

### ISSUE THREAD

**Issue by mdorman** [tkf/emacs-request#31]
`curl` itself tells you this isn't the way to go:

~~~
curl --request HEAD http://google.com/
Warning: Setting custom HTTP method to HEAD may not work the way you want.
~~~

**Comment by syohex** [comment]
You should use `-I` or `--head` option instead of `--request HEAD`.

**Comment by mdorman** [comment]
I don't understand why you closed this.  The problem is that your software *doesn't use -I or --head*.

**Comment by syohex** [comment]
Could you tell us how to reproduce this issue ?

**Comment by mdorman** [comment]
The reproduction recipe is simple: use the curl backend and make a `HEAD` request?  Clearly you have a testing coverage hole.

```
(require 'request)
(request
 "https://wordpress.org/"
 :parser 'buffer-string
 :type "HEAD"
 :error
 (function* (lambda (&key error-thrown &allow-other-keys)
              (message "Got error: %S" error-thrown)))
 :success
 (function* (lambda (&key data &allow-other-keys)
              (when data
                (with-current-buffer (get-buffer-create "*request demo*")
                  (erase-buffer)
                  (insert data)
                  (pop-to-buffer (current-buffer)))))))
```

Produces:

```
Got error: (error . "exited abnormally with code 61
")
```

While a direct call to `curl` with properly constructed arguments works fine:

```
mdorman@aching:~/src/emacs-request (master)$ curl --head https://wordpress.org/
HTTP/2.0 200
server:nginx
date:Tue, 19 Apr 2016 10:03:33 GMT
content-type:text/html; charset=utf-8
vary:Accept-Encoding
strict-transport-security:max-age=360
x-olaf:⛄
x-frame-options:SAMEORIGIN
x-nc:HIT lax 249
```

But this is ultimately unsurprising if you just take two seconds to look at the code!  https://github.com/tkf/emacs-request/blob/master/request.el#L883 clearly does not distinguish between the various types when constructing the `--request` argument, so it blindly adds `--request HEAD`, which, as you so helpfully pointed out, _you shouldn't use_.

**Comment by syohex** [comment]
NOTE: request.el supports POST/GET/PUT/DELETE method. It does not support HEAD method yet.
