### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by cpaulbond** [tkf/emacs-request#32]
I check the documentation and did not see any support for HTTP Authentication.  Did I miss something or is this an upcoming feature? Also, thanks for a great library!

**Comment by ndw** [comment]
+1

I'd like to integrate some elisp with a call to a web service that requires digest auth...

**Comment by DamienCassou** [comment]
I also need that. Currently, I have to do that:

```emacs
(let* ((url-request-method "GET")
       (url-request-extra-headers
        `(("Content-Type" . "application/json")
          ("Authorization" .
           ,(concat "Basic "
                    (base64-encode-string
                     (concat username ":" password)))))))
  (url-retrieve-synchronously url nil t))
```

**Comment by ahonnecke** [comment]
+1

**Comment by hkjels** [comment]
```elisp
:headers `(("Authorization" . ,(concat "Bearer " auth-token)))
```
Seems to work just fine

**Comment by ndw** [comment]
With digest auth? Or only with basic auth?

**Comment by hkjels** [comment]
I've just tried basic auth

**Comment by ndw** [comment]
Right. It's specifically digest auth that I need.

**Comment by titaniumbones** [comment]
@ndw if you can implement this feature (which I don't use and don't know much about) I can merge your solution.

**Comment by ndw** [comment]
I'll put it on my todo list 😄

**Comment by dickmao** [comment]
Sufficiently interested parties should look into adding the `--digest` switch to the curl backend.
