### ISSUE TITLE
Support for UNIX socket?

### ISSUE THREAD

**Issue by Silex** [tkf/emacs-request#35]
Hello,

Is there any plan for this? For information, `make-network-process` supports local UNIX socket, but `url-retrieve` does not.

**Comment by Silex** [comment]
FYI, I found out that this works with curl `curl --unix-socket /var/run/docker.sock http:/images/json`

**Comment by syohex** [comment]
> Is there any plan for this? 

No. However it is not difficult to implement this feature for `curl` backend.
Could you tell us use case of using Unix socket ?

**Comment by Silex** [comment]
@syohex: See https://github.com/Silex/docker-api.el/blob/master/docker-api-connection.el#L31 and https://github.com/Silex/docker-api.el/blob/master/docker-api-connection.el#L66

Basically, to talk to the docker remote api I have to talk over a unix domain socket 99% of the time. Some installations have it as a `tcp://ip:port` instead. Currently I *have* to use `make-network-process` because it's the only way I found in emacs to talk over an UNIX socket.

I just thought it'd be nice to use this lib instead of reinventing my own wheel but maybe I have no choice... yesterday I learnt that errors in the Docker Remote API give `text/plain` answer instead of JSON, so I'll probably need custom parsing in that case.

**Comment by syohex** [comment]
How about #39 ?

**Comment by syohex** [comment]
Done.
