### ISSUE TITLE
Broken encoding 

### ISSUE THREAD

**Issue by o175** [tkf/emacs-request#50]
[After this line](https://github.com/tkf/emacs-request/commit/258c6bf3729eff72aaeb169b4d06f050e8eea565) you'll get hexdumps instead of russian symbols as curl output . Delete this line if it's not needed to fix the output.  I can't grasp what it's intended to do sorry.

**Comment by syohex** [comment]
Please decode data as below in such case.

```lisp
(decode-coding-string data 'utf-8)
```

If encoding of download content is different from system encoding, [mojibake](https://en.wikipedia.org/wiki/Mojibake)(character corruption) may happens without its change. This issue can be avoided by downloading data as binary and encoding it by user.

**Comment by o175** [comment]
Thanks. That worked
