### ISSUE TITLE
Value in GET request is not formatted

### ISSUE THREAD

**Issue by NOBUTOKA** [tkf/emacs-request#51]
I tried to make GET request whose value is string made by format but I get an error "Wrong type argument integerp : format".

I looked over request.el and found cause in request--urlencode-alist function (line 204).
Why do you write "concat (url-hexify-string v)" instead of "concat (url-hexify-string (format "%s" v))"?

**Comment by syohex** [comment]
I suppose it is bug. `value` should be stringified same as `key`.

**Comment by syohex** [comment]
This issue was fixed by #52. Please check latest version.
