### ISSUE TITLE
tramp related execution

### ISSUE THREAD

**Issue by spiderbit** [tkf/emacs-request#59]
I have following problem: 

I use request to send a json message to a webserver in my lan. I have set that to a Shortcut (F6) 
Normaly that works just fine, but if I am in a Eshell window that is connected to another pc over ssh or in a open file that is on another pc accessed through tramp, it just refuses to work.

It looks to me that it tries to execute the curl program then on that pc or something like that?

Is there a way to overwrite the executable url to lets say /~ or /tmp or something like that?

to be more precise I am the author or the package:
https://github.com/spiderbit/kodi-remote.el

which is using request.el to send the json messages to kodi. 

And I bound kodi-remote-music to F6:

  ` (global-set-key (kbd "<f6>") 'kodi-remote-music)`

**Comment by juergenhoetzel** [comment]
> Is there a way to overwrite the executable url to lets say /~ or /tmp or something like that?
> 
> to be more precise I am the author or the package:
> https://github.com/spiderbit/kodi-remote.el

I ran into the same issue. Actually the [Tramp support](https://github.com/tkf/emacs-request/pull/43) has some quirks:

- `curl` backend is chosen even if it is not installed remotely: `executable-find` is evaluated locally to set the `request-backend`
-  Tramp support is not consistent: `url-retrieve` backend doesn't have Tramp support

You might just bind `default-directory` to enforce execution of `curl` on your local machine:

``` elisp
(let ((default-directory nil))
  (request "http://amazon-1d35745cb.fritz.box:8080"
	   :success (cl-function
		     (lambda (&key data &allow-other-keys)
		       (message "OK")))))
```

**Comment by titaniumbones** [comment]
> > Is there a way to overwrite the executable url to lets say /~ or /tmp or something like that?
> > 
> > to be more precise I am the author or the package:
> > https://github.com/spiderbit/kodi-remote.el
>
> I ran into the same issue. Actually the [Tramp support](https://github.com/tkf/emacs-request/pull/43) has some quirks:
>
> - `curl` backend is chosen even if it is not installed remotely: `executable-find` is evaluated locally to set the `request-backend`
> -  Tramp support is not consistent: `url-retrieve` backend doesn't have Tramp support
>
> You might just bind `default-directory` to enforce execution of `curl` on your local machine:
>
> ``` elisp
> (let ((default-directory nil))
>   (request "http://amazon-1d35745cb.fritz.box:8080"
> 	   :success (cl-function
> 		     (lambda (&key data &allow-other-keys)
> 		       (message "OK")))))
> ```

if you have a fix for this issue please feel free to submit a PR, even for the documentation ,and I will merge it!

**Comment by titaniumbones** [comment]
@spiderbit @juergenhoetzel does #82 fix your issue?

**Comment by juergenhoetzel** [comment]
> @spiderbit @juergenhoetzel does #82 fix your issue?

I'm afraid not. #82: is about invalid use of internal `tramp` functions. This issue is about different
behavior when using `request` on remote hosts: `curl` is executed on the remote host  (contrary to the  `url-retrieve` backend).

> if you have a fix for this issue please feel free to submit a PR, even for the documentation ,and I will merge it!

I will check it out. 

Thanks for taking care of this nice Emacs package :+1:

**Comment by juergenhoetzel** [comment]
> if you have a fix for this issue please feel free to submit a PR, even for the documentation ,and I will merge it!

IMO this issue can be closed, because [Tramp support for `curl`](https://github.com/tkf/emacs-request/pull/43) is intended and there is no way to implement `tramp` support using the `url-retrieve` backend.

**Comment by titaniumbones** [comment]
thanks @juergenhoetzel  -- sorry for the slow response. Closing this now!
