### ISSUE TITLE
Http_only cookies are not parsed correctly with curl backend

### ISSUE THREAD

**Issue by millejoh** [tkf/emacs-request#60]
This is because HttpOnly cookies have # at the beginning of the line and so request thinks the cookie is a comment.

As an example this is what the HttpOnly cookie looks like:

#HttpOnly_127.0.0.1	FALSE	/	FALSE	1484255791	username-127-0-0-1-8888	"2|1:0|10:1481663791|23:username-127-0-0-1-8888|44:MjhiYzI0YjYzMTQxNGVjNzg2NzNjZTViNzg1NTg4YWQ=|6852e6f3661848a43acc12fd530bb73b5535664ae063a2d8f03c5e5d40ea44ee"

**Comment by syohex** [comment]
Sorry late response and thanks reporting issue.
I have fixed parser at #61. Could you check it @millejoh ?

**Comment by syohex** [comment]
I have merged #61. Please report us if you still have problem.

**Comment by millejoh** [comment]
Looks good - thanks!
