### ISSUE TITLE
Means for passing additional options to curl

### ISSUE THREAD

**Issue by mfehlhaber** [tkf/emacs-request#66]
So I guess this is a feature request then... I find myself in need to pass `--cacert` and `--noproxy` into `request--curl-command`. Currently I have `request.el` patched, but a customized variable would be so much nicer. Have I overlooked some existing easier way to do this?

**Comment by syohex** [comment]
How about #68 ?

**Comment by mfehlhaber** [comment]
This works very well for me, thank you.

Unfortunately I had to base it on a former version of `request.el` due to a regression introduced in https://github.com/tkf/emacs-request/commit/6e039bf92d576410630d78dc396d0bdc3849b3f2. This might also be due to the way `org-jira` uses your package. See https://github.com/ahungry/org-jira/issues/17 for some context.

**Comment by syohex** [comment]
Add new issue #69.
