### ISSUE TITLE
Regression(?) by 6e039bf

### ISSUE THREAD

**Issue by syohex** [tkf/emacs-request#69]
See https://github.com/tkf/emacs-request/issues/66#issuecomment-272408394

**Comment by titaniumbones** [comment]
@syohex I am going to try to collect solutions for some bugs. Would you be willing to put together a patch to fix this problem?

**Comment by dickmao** [comment]
A three-year-old bug of poorly specified nature that may or may not have been fixed in the meantime.  Sufficiently aggrieved parties should submit a minimum reproducible example.
