### ISSUE TITLE
any tip on installing and usage, please?

### ISSUE THREAD

**Issue by Txellenne** [tkf/emacs-request#71]
Hi, an `[instruction/tip/help]` on **how-to** `(& if possible any reference to tutorials on using web-API/web-queries in the elisp/lisp approach)`**install** `(&/or any tip on usage)` this wonderful package, I'm not a cask user.

**Comment by syohex** [comment]
Add installation documentation at #73. Usage, tips are in documentation, README.md or http://tkf.github.io/emacs-request/

**Comment by titaniumbones** [comment]
Hi, I will be doing what I can, but if you havetime to submit a PR with improved docs that wil lspeed things up!

**Comment by titaniumbones** [comment]
@Txellenne please have a look at current master and see if the current documentation meets your needs.

**Comment by azzamsa** [comment]
Agree, need more usage example.
