### ISSUE TITLE
Wrong localhost with url-retrieve backend on MacOS

### ISSUE THREAD

**Issue by Pitometsu** [tkf/emacs-request#76]
Example:
```elisp
(request (format "http://localhost:%d%s" 8081 "/pnig") :sync t :parser 'buffer-string :timeout 2)
```
does not work, but 0.0.0.0 - does.

**Comment by Pitometsu** [comment]
@tkf any updates here?

**Comment by titaniumbones** [comment]
Hi, I will not be able to fix this eaisly myself but if you have found a fix then I would appreciate a PR  so that I can merge it and make it available to everyone.

**Comment by dickmao** [comment]
I'm afraid hostname translation is not in request.el's bailiwick.  Sorry.

`(request "http://localhost:80" :sync t :parser 'buffer-string :timeout 2)` did work for me on my **Linux** box.
