### ISSUE TITLE
Temp file encoding of curl payloads

### ISSUE THREAD

**Issue by gariepyalex** [tkf/emacs-request#77]
When send an HTTP payload using curl, emacs-request make use of a temp file for the content of the payload. However, when the payloads contains non-ascii characters, the temporary file is encoded in latin1 instead of in utf-8.

The problem seems to come from there:
https://github.com/tkf/emacs-request/commit/fb93d112750b3cddb65dbbf884edbce38cf578fd

Changing the code to:
```elisp
(let ((file-coding-system-alist nil)
             (coding-system-for-write 'utf-8))
         (with-temp-file tempfile
           (setq buffer-file-coding-system 'utf-8)
           (insert data)))
```
seems to fix the problem. I can open a pull request if you want.

**Comment by HIRANO-Satoshi** [comment]
Hi,

We have this issue with org-trello and all of non-English users could not use it. 

@gariepyalex Could you kindly send a PR?

**Comment by MaksVal** [comment]
Hi!

Sorry, but your workaround isn't working for me... I  changed your code a litle:
``` lisp
(setq buffer-file-coding-system 'utf-8)
       (insert data)
       (decode-coding-region (point-min) (point-max) 'utf-8)))
```

**Comment by DamienCassou** [comment]
Matt Price <notifications@github.com> writes:
>  @DamienCassou have you thought about sharing your fork?


I don't want to invest time in maintaining a fork right now.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by titaniumbones** [comment]
Does #85 fix this issue for you @gariepyalex  and @MaksVal ?

**Comment by MaksVal** [comment]
@titaniumbones  this is a fine solution! Thanks!

**Comment by rogorido** [comment]
What is exactly the status of this issue? I have an issue with anki-editor (https://github.com/louietan/anki-editor/issues/51) which seems related to this...

**Comment by dickmao** [comment]
@rogorido We made a backwards incompatible change in release 0.3.1.  louietan/anki-editor#53 updates your package to be compatible with 0.3.1.  #128 attempts to mitigate other fallouts of this kind.

**Comment by MaksVal** [comment]
Yes, thanks you.

пт, 30 нояб. 2018 г., 3:51 Matt Price <notifications@github.com>:
