### ISSUE TITLE
Emacs 24.4 requirement?

### ISSUE THREAD

**Issue by abingham** [tkf/emacs-request#83]
request.el claims that it required emacs 24.4. Is that correct?

**Comment by alphapapa** [comment]
Please see #90.

**Comment by titaniumbones** [comment]
I am willing to update the docs (or accept a PR) but I only have emacs 27.0.50 on my machine and am not so good at exhaustive testing. @abingham do you have reason to believe one way or another?

**Comment by dickmao** [comment]
24.4 is the minimum required version.  Any later versions do get tested and are supposed to work.
