### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by DamienCassou** [tkf/emacs-request#90]
I'm a package author and I would like to know if I can rely on emacs-request. I have the impression this package is not maintained anymore: PRs and issues are not even discussed and the latest commit is more than 1 year old.

**Comment by alphapapa** [comment]
It seems not.  This is concerning to me, as this seems like the most widely used, featureful HTTP library for Emacs.

**Comment by xor-xor** [comment]
Well, maybe it's time to fork this project and give it a second life..? Similar thing already happened with [tkf/emacs-ipython-notebook](https://github.com/tkf/emacs-ipython-notebook/), which is now actively maintained via [millejoh/emacs-ipython-notebook](https://github.com/millejoh/emacs-ipython-notebook/).

**Comment by alphapapa** [comment]
@xor-xor Indeed, however it's a large, complex package, and it's a lot to ask one person to do.  I'd be willing to help maintain it as a team, but I don't feel like I could commit to do it alone.

**Comment by tkf** [comment]
Sorry guys for a very long silence.  I gave committer access to @titaniumbones.

**Comment by titaniumbones** [comment]
@alphapapa @DamienCassou I'm hoping you can help me a bit with fixes that you need in order to support your own packages. This package is a little bit above my skill level!

**Comment by titaniumbones** [comment]
I'm going to close this but will still hope for help from folks here!
