### ISSUE TITLE
Dealing with json request, parser and goodies ~~ from Emacs..

### ISSUE THREAD

**Issue by touxstone** [tkf/emacs-request#91]
Hi, Just to sync with or add some more [examples](https://github.com/tkf/emacs-request/blob/master/README.rst#examples) (happen that I find so puzzling recognizing generic names or references to raw data on those examples (the output is hidden) so here my question: What if I had this following query: `the raw-data is easily visible by just clicking here: ` https://api.datamuse.com/sug?s=rawand which returns the following structure `[{}{}{}] `
and I wanted to get a list of the key/value of the pairs, in the example, I expect to get:
`(rwanda, rwandan, rwandese, lawanda, rowand, rwanda, franc rwandans, rawan, rwandese republic, tawanda)`
 So I prepared this function: 
```elisp
(defun sugestions-from-this (word)
  (request (format "https://api.datamuse.com/sug?s=%s" word))
....)
```
and Using the `*flexible*` parser option (as) shown on [README](https://github.com/tkf/emacs-request/blob/master/README.rst) line 112 I added the following: (nested in the above function) 
```elisp
:parser (lambda () (libxml-parse-html-region (point) (point-max)))
:success (cl-function
                 (lambda (&key data &allow-others-keys)
```
```elisp
                    (let ((get (lambda (node &rest words)
                                     (if words
                                         (apply get
                                                     (first (xml-get-children
                                                       node (car words)))
                                       (cdr words))
                                      (first (xml-node-children node))))))
                       (insert (format "\n %s "
                                                (funcall get data 'entry 'word)))))))
```
I got no success output. I know probably the function is just stuff, not template of nothing as warned but as I cannot check the examples I'm some lost, any gentle help would be appreciated..

**Comment by alphapapa** [comment]
@touxstone 

1.  This library is apparently unmaintained now.  The author is active on GitHub but doesn't seem to respond here anymore.
2.  I can't understand your question or example.
3.  Your question seems to be less about this library and more about parsing with libxml or general elisp.  Please ask it on another forum, like Emacs.SE or /r/emacs.

**Comment by titaniumbones** [comment]
@touxstone I think @alphapapa is correct, but if you can clarify your question and it is relevant to `emacs-request`, I will try to answer it.

**Comment by titaniumbones** [comment]
closing for now, please reopen if appropriate.
